#include "GameMapConfig.h"
float BLOCK_SIZE = 1.0f;
int GAME_MAP_WIDTH_VOXELS = 512;
int GAME_MAP_DEPTH_VOXELS = 512;
int GAME_MAP_HEIGHT_VOXELS = 128;
int TERRAIN_LEAF_CELL_SIZE = 16;
int TERRAIN_MESH_CELL_COUNT = 16;
int MAX_BLOCK = TERRAIN_LEAF_CELL_SIZE;
int GAME_MAP_WIDTH = GAME_MAP_WIDTH_VOXELS / TERRAIN_LEAF_CELL_SIZE;
int GAME_MAP_DEPTH = GAME_MAP_DEPTH_VOXELS / TERRAIN_LEAF_CELL_SIZE;
int GAME_MAP_HEIGHT = GAME_MAP_HEIGHT_VOXELS / TERRAIN_LEAF_CELL_SIZE;
