#pragma once
namespace tzw {
enum class GamePartType
{
	GAME_PART_BLOCK = 0,
	GAME_PART_CYLINDER,
	GAME_PART_LIFT,
	GAME_PART_CONTROL,
	GAME_PART_THRUSTER,
	GAME_PART_CANNON,
	GAME_PART_BEARING,
	GAME_PART_SPRING,
	SPECIAL_PART_PAINTER,
	SPECIAL_PART_DIGGER,
	GAME_PART_NOT_VALID
};
}